import { Artist } from '../core/models';

export const MOCK_ARTISTS: Artist[] = [
  {
    id: 'a1',
    name: 'Luna Vega',
    username: 'lunavega',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&h=400&fit=crop',
    bio: 'Ethereal vocalist blending dream-pop with electronic textures. Based in Berlin. Creating soundscapes that transcend reality.',
    role: 'singer',
    followers: 24500,
    following: 180,
    totalPlays: 1250000,
    socialLinks: {
      spotify: 'https://spotify.com',
      instagram: 'https://instagram.com',
      tiktok: 'https://tiktok.com',
      soundcloud: 'https://soundcloud.com'
    },
    genres: ['Dream Pop', 'Electro', 'Indie'],
    tags: ['dream-pop', 'electronic', 'vocalist', 'berlin-scene'],
    verified: true,
    premium: false,
    joinedDate: '2023-03-15',
    location: 'Berlin, Germany',
    longBio: 'Born in Buenos Aires, raised in Berlin. I started making music in my bedroom with a cheap mic and a borrowed synth. My sound blends ethereal vocals with layered electronic textures — think Cocteau Twins meets Grimes. Every song I write is a postcard from a dream I barely remember.',
    photos: [
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1501612780327-45045538702b?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&h=400&fit=crop'
    ],
    lookingForCollab: true,
    collabDescription: 'Looking for a producer who works with ambient/electronic textures. Open to remote collabs.',
    weeklyGrowth: 12.5
  },
  {
    id: 'a2',
    name: 'KZMA',
    username: 'kzma_beats',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=400&fit=crop',
    bio: 'Producer & beatmaker. Crafting dark trap and experimental hip-hop beats. Type beats available.',
    role: 'producer',
    followers: 18200,
    following: 95,
    totalPlays: 890000,
    socialLinks: {
      spotify: 'https://spotify.com',
      youtubeMusic: 'https://music.youtube.com',
      instagram: 'https://instagram.com'
    },
    genres: ['Trap', 'Hip-Hop', 'Experimental'],
    tags: ['trap', 'type-beats', 'dark-trap', 'producer'],
    verified: true,
    premium: false,
    joinedDate: '2023-01-20',
    location: 'Atlanta, USA',
    longBio: 'Started making beats at 15 in my mom\'s basement. Now I\'ve produced for underground rappers across Atlanta. My sound is dark, heavy, and cinematic. I sell type beats and I\'m always down for a serious collab if the energy matches.',
    lookingForCollab: true,
    collabDescription: 'Looking for rappers and vocalists for a dark trap EP. DM me samples.',
    weeklyGrowth: 8.3
  },
  {
    id: 'a3',
    name: 'The Midnight Collective',
    username: 'midnightcollective',
    avatar: 'https://images.unsplash.com/photo-1526218626217-dc65a29bb444?w=300&h=300&fit=crop',
    cover: 'https://images.unsplash.com/photo-1501612780327-45045538702b?w=1200&h=400&fit=crop',
    bio: 'Indie rock band from Manchester. Raw energy meets poetic lyricism. We play every weekend somewhere in the UK.',
    role: 'band',
    followers: 32100,
    following: 210,
    totalPlays: 2100000,
    socialLinks: {
      spotify: 'https://spotify.com',
      appleMusic: 'https://music.apple.com',
      instagram: 'https://instagram.com',
      tiktok: 'https://tiktok.com'
    },
    genres: ['Indie Rock', 'Alternative', 'Post-Punk'],
    tags: ['indie', 'band', 'live-music', 'manchester', 'guitar'],
    verified: true,
    premium: false,
    joinedDate: '2022-11-10',
    location: 'Manchester, UK',
    longBio: 'Four mates from Manchester who bonded over a love of The Smiths and Arctic Monkeys. We play gritty indie rock with a post-punk edge. Catch us every Friday night somewhere in the north of England.',
    photos: [
      'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&h=400&fit=crop'
    ],
    weeklyGrowth: 15.2
  },
  {
    id: 'a4',
    name: 'Sora Kim',
    username: 'sorakim',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&h=400&fit=crop',
    bio: 'K-pop inspired solo artist. Mixing Korean and English lyrics with modern pop production. Debut EP coming soon.',
    role: 'singer',
    followers: 45300,
    following: 320,
    totalPlays: 3200000,
    socialLinks: {
      spotify: 'https://spotify.com',
      youtubeMusic: 'https://music.youtube.com',
      tiktok: 'https://tiktok.com',
      instagram: 'https://instagram.com'
    },
    genres: ['K-Pop', 'Pop', 'R&B'],
    tags: ['kpop', 'bilingual', 'dancer', 'pop-vocalist'],
    verified: true,
    premium: false,
    joinedDate: '2023-05-01',
    location: 'Seoul, South Korea',
    longBio: 'Half Korean, half American. I grew up between two cultures and my music reflects that duality. Blending K-pop choreography with western pop sensibility. My debut EP drops this summer — every track tells a story of identity.',
    photos: [
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop'
    ],
    weeklyGrowth: 22.1
  },
  {
    id: 'a5',
    name: 'DRVGN',
    username: 'drvgn',
    avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&h=400&fit=crop',
    bio: 'Electronic music producer. From deep house to techno. Resident DJ at Fabric London.',
    role: 'producer',
    followers: 28700,
    following: 150,
    totalPlays: 1800000,
    socialLinks: {
      spotify: 'https://spotify.com',
      soundcloud: 'https://soundcloud.com',
      instagram: 'https://instagram.com'
    },
    genres: ['House', 'Techno', 'Electronic'],
    tags: ['house', 'techno', 'dj', 'club-music', 'london'],
    verified: true,
    premium: false,
    joinedDate: '2022-08-22',
    location: 'London, UK',
    longBio: 'I live for the 4am moment when the whole club is locked in. My sets blend deep house grooves with pounding techno — always building, always moving. Resident at Fabric, touring Europe.',
    lookingForCollab: true,
    collabDescription: 'Looking for vocalists for a deep house EP. Soulful or ethereal voices preferred.',
    weeklyGrowth: 6.8
  },
  {
    id: 'a6',
    name: 'Aria Osei',
    username: 'ariaosei',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&h=400&fit=crop',
    bio: 'Neo-soul vocalist and songwriter. Grammy nominated. Music is my language, rhythm is my poetry.',
    role: 'singer',
    followers: 56800,
    following: 430,
    totalPlays: 4500000,
    socialLinks: {
      spotify: 'https://spotify.com',
      appleMusic: 'https://music.apple.com',
      youtubeMusic: 'https://music.youtube.com',
      instagram: 'https://instagram.com',
      tiktok: 'https://tiktok.com'
    },
    genres: ['Neo-Soul', 'R&B', 'Jazz'],
    tags: ['neo-soul', 'rnb', 'vocalist', 'songwriter', 'afro-soul'],
    verified: true,
    premium: false,
    joinedDate: '2022-06-18',
    location: 'Lagos, Nigeria',
    longBio: 'From the streets of Lagos to stages across Africa and Europe. My music is rooted in Yoruba traditions but speaks a universal language. Neo-soul with jazz harmonies and African rhythms. Every note is a prayer.',
    photos: [
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&h=400&fit=crop'
    ],
    weeklyGrowth: 18.4
  },
  {
    id: 'a7',
    name: 'Nxmbers',
    username: 'nxmbers',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=1200&h=400&fit=crop',
    bio: 'Beatmaker & producer. Lo-fi, boom bap, jazzy vibes. Beats for sale. DM for collabs.',
    role: 'beatmaker',
    followers: 12400,
    following: 88,
    totalPlays: 620000,
    socialLinks: {
      soundcloud: 'https://soundcloud.com',
      instagram: 'https://instagram.com',
      youtubeMusic: 'https://music.youtube.com'
    },
    genres: ['Lo-Fi', 'Boom Bap', 'Jazz Hop'],
    tags: ['lofi', 'boom-bap', 'chill', 'beats-for-sale', 'jazz'],
    verified: false,
    premium: false,
    joinedDate: '2023-09-05',
    location: 'Tokyo, Japan',
    longBio: 'Making beats between Tokyo rain and vinyl crackle. Lo-fi, boom bap, jazzy vibes — all made with hardware samplers and dusty records. Beats available for lease.',
    lookingForCollab: true,
    collabDescription: 'Looking for rappers who vibe with lo-fi/boom bap beats. Chill stuff only.',
    weeklyGrowth: 5.1
  },
  {
    id: 'a8',
    name: 'Velvet Rust',
    username: 'velvetrust',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&h=400&fit=crop',
    bio: 'Multi-instrumentalist. Guitar, keys, synths. Creating cinematic soundscapes for the modern age.',
    role: 'musician',
    followers: 15600,
    following: 210,
    totalPlays: 780000,
    socialLinks: {
      spotify: 'https://spotify.com',
      soundcloud: 'https://soundcloud.com',
      instagram: 'https://instagram.com'
    },
    genres: ['Ambient', 'Cinematic', 'Post-Rock'],
    tags: ['ambient', 'cinematic', 'multi-instrumentalist', 'soundtrack'],
    verified: false,
    premium: false,
    joinedDate: '2023-07-12',
    location: 'Reykjavik, Iceland',
    longBio: 'Inspired by the Icelandic landscape — glaciers, volcanoes, silence. I play guitar, keys, and synths, layering them into cinematic soundscapes. Music for films, games, and moments of introspection.',
    photos: [
      'https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=600&h=400&fit=crop'
    ],
    lookingForCollab: true,
    collabDescription: 'Looking for filmmakers or game devs who need original scores. Also open to post-rock collabs.',
    weeklyGrowth: 3.7
  },
  {
    id: 'a9',
    name: 'PRXZM',
    username: 'prxzm',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1508854710579-5cecc3a9ff17?w=1200&h=400&fit=crop',
    bio: 'Future bass & melodic dubstep producer. Festival-ready drops and emotional breakdowns.',
    role: 'producer',
    followers: 21300,
    following: 167,
    totalPlays: 1100000,
    socialLinks: {
      spotify: 'https://spotify.com',
      soundcloud: 'https://soundcloud.com',
      youtubeMusic: 'https://music.youtube.com'
    },
    genres: ['Future Bass', 'Dubstep', 'EDM'],
    tags: ['future-bass', 'edm', 'festival', 'melodic-dubstep'],
    verified: true,
    premium: false,
    joinedDate: '2023-02-28',
    location: 'Los Angeles, USA',
    longBio: 'Festival-ready drops and emotional breakdowns. I make music that hits you in the chest and the heart at the same time. Premiered tracks at EDC and Tomorrowland.',
    weeklyGrowth: 9.6
  },
  {
    id: 'a10',
    name: 'Mila Ortiz',
    username: 'milaortiz',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face',
    cover: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=1200&h=400&fit=crop',
    bio: 'Latin pop meets reggaeton. Bilingual artist breaking barriers. Featured on Billboard Latin charts.',
    role: 'singer',
    followers: 67200,
    following: 290,
    totalPlays: 5800000,
    socialLinks: {
      spotify: 'https://spotify.com',
      appleMusic: 'https://music.apple.com',
      tiktok: 'https://tiktok.com',
      instagram: 'https://instagram.com'
    },
    genres: ['Latin Pop', 'Reggaeton', 'Pop'],
    tags: ['latin', 'reggaeton', 'bilingual', 'latin-pop', 'miami'],
    verified: true,
    premium: false,
    joinedDate: '2022-04-10',
    location: 'Miami, USA',
    longBio: 'Born in Medellín, raised in Miami. I sing in Spanish and English because my heart speaks both. Latin pop with reggaeton fire — I want my music to make you move and feel at the same time. Billboard Latin charted.',
    photos: [
      'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1571075051280-29b8faee2cb7?w=600&h=400&fit=crop'
    ],
    weeklyGrowth: 25.3
  }
];
