import { Collaboration } from '../core/models';

export const MOCK_COLLABORATIONS: Collaboration[] = [
  {
    id: 'c1',
    title: 'Vocalist needed for dark trap EP',
    description: 'Working on a 5-track EP with heavy 808s and cinematic pads. Need a rapper or singer who can deliver intense, emotional bars. Must be comfortable with dark themes. Remote collab via stems.',
    authorId: 'a2',
    authorName: 'KZMA',
    authorUsername: 'kzma',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    authorRole: 'Producer',
    category: 'vocalist',
    genres: ['Trap', 'Hip-Hop'],
    status: 'open',
    createdAt: '2024-04-14T14:00:00Z',
    responses: 12,
    tags: ['trap', 'vocals', 'dark', 'ep']
  },
  {
    id: 'c2',
    title: 'Producer for ambient/electronic EP',
    description: 'I write dreamy vocals and melodies but I need someone who can build the sonic world around them. Think Cocteau Twins meets Grimes. Must work with Ableton or Logic. Berlin-based preferred but remote OK.',
    authorId: 'a1',
    authorName: 'Luna Vega',
    authorUsername: 'lunavega',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    authorRole: 'Singer',
    category: 'producer',
    genres: ['Dream Pop', 'Electronic'],
    status: 'open',
    createdAt: '2024-04-13T10:00:00Z',
    responses: 8,
    tags: ['ambient', 'electronic', 'dream-pop', 'vocals']
  },
  {
    id: 'c3',
    title: 'Soulful vocalist for deep house tracks',
    description: 'I produce deep house and I\'m looking for a vocalist who can deliver soulful, emotive performances. Think Disclosure-style vocal chops mixed with full vocal takes. Royalty split negotiable.',
    authorId: 'a5',
    authorName: 'DRVGN',
    authorUsername: 'drvgn',
    authorAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face',
    authorRole: 'Producer',
    category: 'vocalist',
    genres: ['House', 'Deep House'],
    status: 'open',
    createdAt: '2024-04-12T16:00:00Z',
    responses: 15,
    tags: ['house', 'vocals', 'soulful', 'deep-house']
  },
  {
    id: 'c4',
    title: 'Guitarist for post-rock project',
    description: 'Working on cinematic post-rock tracks that need a guitarist who can do ambient swells, delay-drenched arpeggios, and explosive crescendos. Think Explosions in the Sky. Remote via stems.',
    authorId: 'a8',
    authorName: 'Velvet Rust',
    authorUsername: 'velvetrust',
    authorAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=100&h=100&fit=crop&crop=face',
    authorRole: 'Musician',
    category: 'guitarist',
    genres: ['Post-Rock', 'Ambient'],
    status: 'open',
    createdAt: '2024-04-11T12:00:00Z',
    responses: 6,
    tags: ['guitar', 'post-rock', 'ambient', 'cinematic']
  },
  {
    id: 'c5',
    title: 'Rapper for lo-fi boom bap beats',
    description: 'Got a whole tape of lo-fi boom bap beats ready. Looking for a rapper with a chill flow who can spit bars about real life stuff. Think Earl Sweatshirt meets MIKE. Beats are free for the right person.',
    authorId: 'a7',
    authorName: 'Nxmbers',
    authorUsername: 'nxmbers',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    authorRole: 'Beatmaker',
    category: 'vocalist',
    genres: ['Lo-Fi', 'Boom Bap'],
    status: 'open',
    createdAt: '2024-04-10T20:00:00Z',
    responses: 9,
    tags: ['lofi', 'rapper', 'boom-bap', 'chill']
  },
  {
    id: 'c6',
    title: 'Mixing engineer for debut album',
    description: 'Our debut album "Wired" is recorded but needs professional mixing. 10 tracks, indie rock/post-punk. Recorded live in a warehouse. We need someone who can keep the raw energy while cleaning it up.',
    authorId: 'a3',
    authorName: 'The Midnight Collective',
    authorUsername: 'midnightcollective',
    authorAvatar: 'https://images.unsplash.com/photo-1526218626217-dc65a29bb444?w=100&h=100&fit=crop',
    authorRole: 'Band',
    category: 'mixing',
    genres: ['Indie Rock', 'Post-Punk'],
    status: 'in_progress',
    createdAt: '2024-04-08T14:00:00Z',
    responses: 22,
    tags: ['mixing', 'indie', 'rock', 'album']
  },
  {
    id: 'c7',
    title: 'Songwriter for K-pop inspired tracks',
    description: 'Looking for a songwriter who can write catchy hooks in English for K-pop style production. I handle the Korean lyrics but need someone for the English bridges and choruses. Debut EP project.',
    authorId: 'a4',
    authorName: 'Sora Kim',
    authorUsername: 'sorakim',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    authorRole: 'Singer',
    category: 'songwriter',
    genres: ['K-Pop', 'Pop'],
    status: 'open',
    createdAt: '2024-04-09T11:00:00Z',
    responses: 18,
    tags: ['songwriter', 'kpop', 'english', 'hooks']
  },
  {
    id: 'c8',
    title: 'Beatmaker for reggaeton fusion project',
    description: 'Working on a new project that fuses reggaeton with other Latin genres — cumbia, bachata, merengue but with a modern twist. Need a beatmaker who knows Latin rhythms AND modern production. Big project, multiple tracks.',
    authorId: 'a10',
    authorName: 'Mila Ortiz',
    authorUsername: 'milaortiz',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    authorRole: 'Singer',
    category: 'beatmaker',
    genres: ['Reggaeton', 'Latin Pop'],
    status: 'open',
    createdAt: '2024-04-07T15:00:00Z',
    responses: 31,
    tags: ['reggaeton', 'latin', 'beatmaker', 'fusion']
  }
];
